export const projects = [
  {
    id: '1',
    img: '/images/projects/twitter-clone.png',
    name: 'Twitter Clone',
    desc: 'Twitter clone using MERN stack',
    link: 'https://github.com/youngjun114/twitter',
    category: 'backend',
  },
  {
    id: '2',
    img: '/images/projects/youtube-clone.png',
    name: 'Youtube Clone',
    desc: 'Youtube clone using React JS and Youtube API',
    link: 'https://github.com/youngjun114/youtube-revised',
    category: 'frontend',
  },
  {
    id: '3',
    img: '/images/projects/netflix-clone.png',
    name: 'Netflix Clone',
    desc: 'Netflix clone using React JS and TMDB API and Firebase Authentication',
    link: 'https://github.com/youngjun114/netflix-clone',
    category: 'frontend',
  },
  {
    id: '4',
    img: '/images/projects/card-maker.png',
    name: 'Business Card Maker',
    desc: 'Card maker using React JS, Firebase Realtime Database, Firebase Authentication, and Cloudinary',
    link: 'https://github.com/youngjun114/card-maker',
    category: 'frontend',
  },
  {
    id: '5',
    img: '/images/projects/web-design.png',
    name: 'Web Design',
    desc: 'Simple web design with React',
    link: 'https://github.com/youngjun114/gallery',
    category: 'frontend',
  },
  {
    id: '6',
    img: '/images/projects/carrot-game.png',
    name: 'Carrot Game',
    desc: 'Finding carrot game with HTML, CSS, and Vanilla Javascript',
    link: 'https://github.com/youngjun114/javscript/tree/main/carrot-game',
    category: 'frontend',
  },
];
